name:         freetype-gl-mini
version:      "0.1"
category:     Graphics
synopsis:     Text rendering with freetype-gl
description:  Text rendering with freetype-gl
license:      BSD3
author:       Luke Iannini
copyright:    Luke Iannini
maintainer:   lukexi@me.com
github:       lukexi/freetype-gl-mini

ghc-prof-options:    -Wall -O2 -fprof-auto
ghc-options:         -Wall -O2

dependencies:
  - base
  - stm 
  - gl 
  - linear 
  - gl-pal
  - glfw-pal 
  - containers 
  - mtl 
  - lens-extra 

library:
  source-dirs:
    - src
  c-sources:
    - cbits/helpers.c
    - freetype-gl/texture-font.c
    - freetype-gl/texture-atlas.c
    - freetype-gl/vector.c
    - freetype-gl/platform.c
  include-dirs:
    - freetype-gl/windows/freetype/
    - freetype-gl/
  when:
    condition: os(windows)
    then:
      extra-libraries: freetype-6
      extra-lib-dirs: c:\msys64\mingw64\bin
      include-dirs: C:\msys64\mingw64\include
    else:
      extra-libraries: freetype